/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class QuotationAddIcon {
  QuotationAddIcon._();

  static const _kFontFam = 'Quotation_saugat_add_icon';
  static const _kFontFam1 = 'CategoryIcon';
  // static const String _kFontPkg = "icons/CategoryIcon";

  static const IconData iUe800 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData categoryIcon =
      const IconData(0xe800, fontFamily: _kFontFam1);
}
