// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy7WhgbP7PilGE-65k6BLPJ4aPPRIRqrw',
    appId: '1:803082167987:web:3c6668416ae86dec7ff2c6',
    messagingSenderId: '803082167987',
    projectId: 'shamagri-demo',
    authDomain: 'shamagri-demo.firebaseapp.com',
    databaseURL: 'https://shamagri-demo.firebaseio.com',
    storageBucket: 'shamagri-demo.appspot.com',
    measurementId: 'G-F5T59FZVK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7OasrlJPcUItbpyGp6kI84yLM7PNTTJs',
    appId: '1:803082167987:android:a281b16dfbba2fc97ff2c6',
    messagingSenderId: '803082167987',
    projectId: 'shamagri-demo',
    databaseURL: 'https://shamagri-demo.firebaseio.com',
    storageBucket: 'shamagri-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy7WhgbP7PilGE-65k6BLPJ4aPPRIRqrw',
    appId: '1:803082167987:ios:b42a6a5adc6b1c147ff2c6',
    messagingSenderId: '803082167987',
    projectId: 'shamagri-demo',
    databaseURL: 'https://shamagri-demo.firebaseio.com',
    storageBucket: 'shamagri-demo.appspot.com',
    androidClientId: '803082167987-8nqkhiq4pero9n81957g5d5gtb7g6vfa.apps.googleusercontent.com',
    iosClientId: '803082167987-9kic15jeldcalgudfrl9dblp7660bth4.apps.googleusercontent.com',
    iosBundleId: 'com.shamagri.shamagri26',
  );
}
